### ISSUE TITLE
More directly edit unit stats?

### ISSUE THREAD

**Issue by DarkInsignia** [oscarpedrero/BloodyEncounters#4]
Hey, I love the mod, however I was curious if it would be possible to more directly edit unit stats? (In both bloodyencounters and bloodyboss)

For example, I'd like to make encounters with specific keywords, to which you can identify in which field the characters are a little bit buffed/what their weaknesses are etc.

E.g.:
  "health": {
    "maxHealth": 89.482605,
    "value": 89.48,
    "maxRecoveryHealth": 1
  },
  "unitStats": {
    "physicalCriticalStrikeDamage": 2,
    "spellCriticalStrikeDamage": 2,
    "physicalPower": 19.696924,
    "spellPower": 19.696924,
    "resourcePower": 18,
    "siegePower": 8,
    "resourceYieldModifier": 1,
    "reducedResourceDurabilityLoss": 1,
    "passiveHealthRegen": 1,
    "healthRecovery": 1,
    "shieldAbsorbModifier": 1,
    "bloodEfficiency": 1

**Comment by oscarpedrero** [comment]
Yes, in principle you could change the statistics of NPCs or bosses, but it would be very complex to configure them from the command line. I'll think of a way to do it soon and I'll tell you what, thanks for the idea and your feedback ;)

I'll leave the ticket open for when I get to work on it.

**Comment by DarkInsignia** [comment]
Even if it would HAVE to be through the text file in the config folder, it would already be so much easier for any non programmer to do it than without!

I'd say don't worry about the command lines too much :)

**Comment by oscarpedrero** [comment]
This option is now available in the latest version of the mod
